# Windows Error

name: WindowsErr

# Works
on:
  # Triggers the workflow on push or pull request events but only for the "Develop" branch
  push:
    branches: [ "Develop" ]
  pull_request:
    branches: [ "Develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: PocketAPI/checkerrors@v1

      # Detecting the commit
      - name: Detect
        run: echo Oh No! We have detected an error!

      # displays the test result
      - name: Test results
        run: |
          echo Commit Failed
          echo The problem is : Unknown
      # displays the test log
      - name: Test log
        run: |
          echo Testing the commit 
          echo Detecting...
          echo 1/15 checks
          echo 2/15 checks
          echo 3/15 checks
          echo 4/15 checks
          echo 5/15 checks
          echo 6/15 checks
          echo 7/15 checks
          echo 8/15 checks
          echo 9/15 checks
          echo 10/15 checks
          echo 11/15 checks
          echo 12/15 checks
          echo 13/15 checks
          echo 14/15 checks
          echo 15/15 checks
          echo Attempt 1 failed ; Reason : Error detected!
          echo Attempt 2 started
          echo 15/15 checks
          echo Attempt 2 failed ; Reason : Error detected!
          echo Final attempt started
          echo 15/15 checks
          echo Test Failed!!!
          echo Error Detected!!!
      # Post test log
      - name: Post test log
        run : |
          echo Test failed
          echo ending
      # Cleanup
      - name: Cleanup
        run: echo Cleanup finished
      # Post job
      - name: Post Job
        run: echo Job finished unsuccessfully
